// frontend/candidate/src/app/core/header/header.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  @Input() isAuthenticated = false;

  constructor(
    private readonly router: Router
  ) { }

  ngOnInit(): void {}

  onLogout(): void {
    localStorage.removeItem('token');
    this.router.navigate(['login']);
    this.isAuthenticated = false;
  }
}

<header class="sticky z-50 bg-white border-b">
  <div class="container mx-auto">
    <div class="grid grid-cols-12 items-center">
      <aside class="col-span-2">
        <h1 class="uppercase font-bold text-2xl">
          <a routerLink="/">
            <span class="text-indigo-500">Ute</span> Recruitment
          </a>
        </h1>
      </aside>
      <aside class="col-span-6">
        <nav class="pl-8">
          <ul class="flex">
            <li class="px-6">
              <a
                routerLink="/"
                [routerLinkActiveOptions]="{exact: true}"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                Home
              </a>
            </li>
            <li class="px-6">
              <a
                routerLink="/jobs"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                Jobs
              </a>
            </li>
            <li class="px-6">
              <a
                routerLink="/employers"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                Employers
              </a>
            </li>
            <li class="px-6">
              <a
                routerLink="/packages"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                Packages
              </a>
            </li>
            <li class="px-6">
              <a
                routerLink="/packages"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                About
              </a>
            </li>
            <li class="px-6">
              <a
                routerLink="/contact"
                class="text-sm text-gray-700 py-8 inline-block border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500"
                routerLinkActive="text-indigo-500 border-b-2 border-indigo-500"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>
      </aside>
      <aside class="col-span-4">
        <div class="float-right">
          <ul class="flex items-center">
            <li *ngIf="!isAuthenticated">
              <a
                routerLink="/register"
                class="focus:outline-none px-4 inline-block text-sm text-indigo-500 hover:text-indigo-400 hover:underline"
              >
                Register
              </a>
            </li>
            <li *ngIf="!isAuthenticated">
              <a
                routerLink="/login"
                class="focus:outline-none px-4 inline-block text-sm text-indigo-500 hover:text-indigo-400 hover:underline"
              >
                Login
              </a>
            </li>
            <li *ngIf="isAuthenticated">
              <a nz-dropdown [nzDropdownMenu]="menu" class="text-indigo-500 hover:text-indigo-300">
                My Account
              </a>
              <nz-dropdown-menu #menu="nzDropdownMenu">
                <ul nz-menu>
                  <li
                    routerLink="account/profile"
                    class="focus:outline-none py-2 px-4 hover:bg-gray-100 cursor-pointer">
                    Profile
                  </li>
                  <li
                    routerLink="account/resume"
                    class="focus:outline-none py-2 px-4 hover:bg-gray-100 cursor-pointer">
                    Resume
                  </li>
                  <li
                    routerLink="account/change-password"
                    class="focus:outline-none py-2 px-4 hover:bg-gray-100 cursor-pointer">
                    Change Password
                  </li>
                  <li
                    (click)="onLogout()"
                    class="focus:outline-none py-2 px-4 hover:bg-gray-100 cursor-pointer">
                    Logout
                  </li>
                </ul>
              </nz-dropdown-menu>
            </li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
</header>

// frontend/employer/src/components/header.tsx
import React from "react";
import { NavLink } from "react-router-dom";
import { useMe } from "../hooks/useMe";

export const Header: React.FC = () => {
  const { data } = useMe();
  return (
    <header className="shadow border-b">
      <div className="container mx-auto flex justify-between items-center">
        <h1 className="uppercase text-2xl font-bold"><span className="text-indigo-500">Ute</span> Recruitment</h1>
        <nav>
          <ul className="flex space-x-2">
            <li>
              <NavLink
                to="/"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Home
              </NavLink>
              <NavLink
                to="/services"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Services
              </NavLink>
              <NavLink
                to="/packages"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Packages
              </NavLink>
              <NavLink
                to="/login"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Login
              </NavLink>
              <NavLink
                to="/register"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Register
              </NavLink>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
};
