// frontend/employer/src/components/header.tsx
import React from "react";
import { NavLink } from "react-router-dom";
import { useMe } from "../hooks/useMe";

export const Header: React.FC = () => {
  const { data } = useMe();
  return (
    <header className="shadow border-b">
      <div className="container mx-auto flex justify-between items-center">
        <h1 className="uppercase text-2xl font-bold"><span className="text-indigo-500">Ute</span> Recruitment</h1>
        <nav>
          <ul className="flex space-x-2">
            <li>
              <NavLink
                to="/"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Home
              </NavLink>
              <NavLink
                to="/services"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Services
              </NavLink>
              <NavLink
                to="/packages"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Packages
              </NavLink>
              <NavLink
                to="/login"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Login
              </NavLink>
              <NavLink
                to="/register"
                className="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-teal-500 hover:border-teal-500"
                activeClassName="text-teal-500 border-teal-500">
                Register
              </NavLink>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
};

// frontend/employer/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  isLogged: boolean;

  constructor() { }

  ngOnInit(): void {
    this.isLogged = true;
  }

}

<header class="shadow border-b">
  <div class="container mx-auto flex justify-between items-center">
    <h1 class="uppercase text-2xl font-bold"><span class="text-indigo-500">Ute</span> Recruitment</h1>
    <nav>
      <ul class="flex space-x-2">
        <li>
          <a
            routerLink="/company"
            routerLinkActive="text-indigo-500 border-indigo-500"
            [routerLinkActiveOptions]="{exact: true}"
            class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
            My Company
          </a>
        </li>
        <ng-template [ngIf]="isLogged">
          <li>
            <a
              routerLink="/resumes"
              routerLinkActive="text-indigo-500 border-indigo-500"
              class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
              Manager Resumes
            </a>
          </li>
          <li>
            <a
              routerLink="/find-candidates"
              routerLinkActive="text-indigo-500 border-indigo-500"
              class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
              Find candidates
            </a>
          </li>
          <li>
            <a
              routerLink="/jobs"
              routerLinkActive="text-indigo-500 border-indigo-500"
              class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
              Jobs Recruitment
            </a>
          </li>
        </ng-template>
        <li *ngIf="!isLogged">
          <a
            routerLink="/services"
            routerLinkActive="text-indigo-500 border-indigo-500"
            class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
            Services
          </a>
        </li>
        <li>
          <a
            routerLink="/packages"
            routerLinkActive="text-indigo-500 border-indigo-500"
            class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
            Packages
          </a>
        </li>
        <ng-template [ngIf]="!isLogged">
          <li>
            <a
              routerLink="/login"
              routerLinkActive="text-indigo-500 border-indigo-500"
              class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
              Login
            </a>
          </li>
          <li>
            <a
              routerLink="/register"
              routerLinkActive="text-indigo-500 border-indigo-500"
              class="inline-block py-6 px-4 text-gray-900 font-medium capitalize border-b-2 border-transparent hover:text-indigo-500 hover:border-indigo-500">
              Register
            </a>
          </li>
        </ng-template>
        <li *ngIf="isLogged">
          <button class="focus:outline-none py-6 px-4 text-gray-900 font-medium hover:text-indigo-500 flex items-center">
            Account
            <svg
              class="w-3 h-3 ml-1"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2" d="M19 9l-7 7-7-7">
              </path>
            </svg>
          </button>
        </li>
      </ul>
    </nav>
  </div>
</header>
